### ISSUE TITLE
Morning session: Peer to peer code review

### ISSUE THREAD

**Issue by prolajumokeoni** [rpire/leaderboard#4]
#### ♻️ Here are the few suggestions we raised this morning at the morning session:
- You should add a limit to numbers that can be added to the scores by users

`else if (points.value.length < 1 || points.value === '.') {
    name.style.borderColor = 'black';
    points.style.borderColor = 'red';
    msg.innerHTML = '**please enter your score**';`

- Also you can set up github pages so you do not need to add a path to your deployed link

**Comment by rpire** [comment]
### Thank you 🙌

Thank you for reviewing my work. I will make sure to implement these changes soon. 🤓

Cheers and Happy coding! 🚀
